### ISSUE TITLE
登录后台提示这个Request method 'POST' not supported

### ISSUE THREAD

**Issue by ludashi2020** [onlyGuo/dnf-server-public#1]
ERROR 939 --- [nio-9001-exec-8] w.s.m.m.RequestMappingInfoHandlerMapping : Request method 'POST' not supported

![pic](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-17a2be90-3ea0-49c5-bf3b-cdaa9d8159f9/aa2233be-3d98-4331-9e9a-857afd552fb4.png)

**Comment by ludashi2020** [comment]
[http-nio-9001-exec-1] w.s.m.m.RequestMappingInfoHandlerMapping : Request method 'POST' not supported

**Comment by onlyGuo** [comment]
拉取最新代码并编译就好了
