### ISSUE TITLE
用bat文件使用client/login接口生成的token登录DNF.exe在选择角色界面出现“因服务期和频道之间的数据传送出现延迟，网络联接将被中断”

### ISSUE THREAD

**Issue by Suntz246** [onlyGuo/dnf-server-public#2]
![QQ截图20220422065414](https://user-images.githubusercontent.com/49502214/164569720-be1e97d0-8056-4b6f-a606-1d21e2e29cfc.png)
![image](https://user-images.githubusercontent.com/49502214/164569758-088281d5-d42d-4d12-8b54-e5e79a1ff50e.png)
![image](https://user-images.githubusercontent.com/49502214/164569788-8886f132-48fb-46d8-851c-084f9c11ad90.png)

**Comment by onlyGuo** [comment]
检查客户端和server中的公私钥是否一致。

**Comment by onlyGuo** [comment]
检查生成token时的公私钥与dnfserver中的公私钥是否一致
